### ISSUE TITLE
skill issue

### ISSUE THREAD

**Issue by azazazo** [PythonRocks1234/redsun#2]
seethe cope cry about it
![sus_furret](https://user-images.githubusercontent.com/65768823/142622999-d9ea7942-304c-41d2-bd23-5f7527bfda20.png)

**Comment by PythonRocks1234** [comment]
I am sorry this repository did not meet your standards. Please feedback here on how we can improve this repository.

**Comment by PythonRocks1234** [comment]
damn i really havin skill issue

my code bad!!!!! :vomiting face:

**Comment by azazazo** [comment]
> I am sorry this repository did not meet your standards. Please feedback here on how we can improve this repository.

dont care + didnt ask + cope + ratio L

**Comment by PythonRocks1234** [comment]
closed :trollface:

**Comment by Wang-Zerui** [comment]
opened :trollface:

**Comment by PythonRocks1234** [comment]
its still closed

**Comment by Wang-Zerui** [comment]
:(

**Comment by PythonRocks1234** [comment]
trolled
